# Note that this is a slimmed version of a detekt config file that only includes behavior we
# want to override for our application. This is done by using `buildUponDefaultConfig` in the gradle
# configuration.

comments:
  UndocumentedPublicClass:
    active: false
    excludes: [
      '**/dto/**',
      '**/models/**',
      '**/displaymodels/**',
      '**/test/**',
      '**/androidTest/**',
      '**/commonTest/**',
      '**/androidUnitTest/**',
      '**/androidInstrumentedTest/**',
      '**/iosTest/**'
    ]
    # Coming soon
#    ignoreDefaultCompanionObject: true
    searchInNestedClass: true
    searchInInnerClass: true
    searchInInnerObject: true
    searchInInnerInterface: true
naming:
  FunctionNaming:
    active: true
    excludes: [ '**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/androidUnitTest/**', '**/androidInstrumentedTest/**', '**/jsTest/**', '**/iosTest/**' ]
    functionPattern: '[a-z][a-zA-Z0-9]*'
    excludeClassPattern: '$^'
    ignoreAnnotated: [ 'Composable' ]
  MatchingDeclarationName:
    active: true
    excludes: [ '**/androidMain/**', '**/iosMain/**', '**/desktopMain/**' ]
style:
  MagicNumber:
    excludes: [ '**/test/**', '**/*Test.kt', '**/*Spec.kt' ]
    ignorePropertyDeclaration: true
    ignoreAnnotation: true
    ignoreEnums: true
    ignoreNumbers:
      - '-1'
      - '0'
      - '1'
      - '2'
      - '0.5'